# **Notebook 1 – Introduction to NumPy**

## **1. What is NumPy?**

**Understand the Concept**

- NumPy means Numerical Python.
- It is a Python library used to work with numbers and data.
- It helps us store many numbers in an array.
- It also makes mathematical calculations easier and faster.
- NumPy is commonly used in Data Science, AI, and Machine Learning.

**Demonstrate the Concept**

**Real-Life Example:**

A gym can store the weights used in different workouts 

**AI/ML Example:**

Almost every Machine Learning dataset is converted into NumPy arrays before training a model because mathematical calculations are much faster.

In [1]:
# Import numpy libraries
import numpy as np

In [3]:
gym = np.array([20, 25, 30, 30, 35])
print(gym)

[20 25 30 30 35]


## **2. Why NumPy?**

**Understand the Concept**

- NumPy makes it easy to work with large amounts of numerical data.
- It is faster than Python lists for many numerical operations.
- We can perform calculations on many values at the same time.
- It provides many useful functions for mathematical and statistical calculations.

In [5]:
# Implement the Concept:
python_list = [1,2,3,4]

numpy_array = np.array([1,2,3,4])

print(type(python_list))
print(type(numpy_array))

<class 'list'>
<class 'numpy.ndarray'>


## **3. NumPy Arrays (ndarray)**



**Understand the Concept**

- A NumPy array is used to store multiple values in one place.
- A NumPy array can store numbers, text, or other types of data.
- Arrays can have one or more dimensions.
- Unlike Python lists, NumPy arrays are homogeneous.

**AI/ML Usage :** Dataset features are usually stored as NumPy arrays before training models.




In [6]:
# Implement the Concept:
# Create a NumPy array
marks = np.array([78, 85, 92, 67, 88])

print("Marks:", marks)
print(type(marks))

Marks: [78 85 92 67 88]
<class 'numpy.ndarray'>


## **4. Creating Arrays**



**Understand the Concept**

- NumPy provides different ways to create arrays.
- We can create an array using `np.array()`.
- We can also create arrays filled with zeros or ones.
- We can create a range of numbers using `np.arange()`.





In [8]:
# Implement the Concept:
# Creating a array in different ways
# using values
marks = np.array([70, 80, 90])

# array of zeros
zeros = np.zeros(3)

# array of ones
ones = np.ones(3)

#  array of range
numbers = np.arange(1, 6)

print("Marks:", marks)
print("Zeros:", zeros)
print("Ones:", ones)
print("Numbers:", numbers)

Marks: [70 80 90]
Zeros: [0. 0. 0.]
Ones: [1. 1. 1.]
Numbers: [1 2 3 4 5]


## **5. Dimensions**



**Understand the Concept**

- Dimension tells us how many levels an array has.
- 1D array -  single row of values.
- 2D array - rows and columns.
- 3D array - contain multiple 2D arrays.




**Demonstrate the Concept**

**Example:**

* 1D array: [10, 20, 30, 40]
* 2D array: [[10, 20], [30, 40]]
* 3D array: [[[1,2],[3]],[[4],[5,6]]


**AI/ML Example:**

ML data is often stored as a 2D array where rows represent data records and columns represent features.



In [17]:
# Implement the Concept:
# Create a 1D array
one_d = np.array([10, 20, 30, 40])

# Create a 2D array
two_d = np.array([[10, 20], [30, 40]])

# Create a 3D array
three_d = np.array([[[10,20],[30,40]],
                    [[40,50],[60,70]]])

print("1D Array:", one_d)
print("\n2D Array:\n",two_d)
print("\n3D Array:\n",three_d)


1D Array: [10 20 30 40]

2D Array:
 [[10 20]
 [30 40]]

3D Array:
 [[[10 20]
  [30 40]]

 [[40 50]
  [60 70]]]


In [18]:
print("Type :",one_d.ndim,"D")
print("Type :",two_d.ndim,"D")
print("Type :",three_d.ndim,"D")


Type : 1 D
Type : 2 D
Type : 3 D


## **6. Shape**



**Understand the Concept**

- Shape tells us the size of an array in each dimension.
- It tells us the number of rows and columns in a 2D array.





**Demonstrate the Concept**

**Real-Life Example:**

- A college has marks for 4 students in 3 subjects.


**AI/ML Example:**

- Before training a model, checking the dataset shape ensures the data is in the correct format.

In [22]:
# Implement the Concept:
# data in 2D array
marks = np.array([[80, 75, 90],
                  [70, 54, 99],
                  [84, 75, 89],
                  [85, 88, 92]])


print(marks) # 4 row , 3 col
print("Shape:", marks.shape)

[[80 75 90]
 [70 54 99]
 [84 75 89]
 [85 88 92]]
Shape: (4, 3)


## **7. Size**




**Understand the Concept**

- Size tells us the total number of values in an array.





**Demonstrate the Concept**


**AI/ML Example:**

Suppose a dataset has 100 records and 5 features. If it is stored as a NumPy array, the total number of values is: 100 × 5 = 500


In [24]:
# Implement the Concept:
# Create a 2D array
marks = np.array([[80, 75, 90],
                  [85, 88, 92]])
# row * col = size
print("Shape:", marks.shape)
print("Size:", marks.size)

Shape: (2, 3)
Size: 6


## **8. Data Types**



**Understand the Concept**

- Data type tells us what type of value is stored in an array.
- NumPy supports different data types such as integers, decimal numbers, and text.




**Demonstrate the Concept**

**Real-Life Example:**

- A shopping application may store product prices 

**AI/ML Usage:**

- Used to check and choose suitable data types for numerical data before processing a dataset.


In [27]:
# Implement the Concept:
# decimal - product prices 
price = np.array([459.89, 620.50, 299.99, 89.45])

# integer - product count
count = np.array([38,29,55,12])
print("Count:", count)
print("Count Data Type:", count.dtype)

print("\nPrice:", price)
print("Price Data Type:", price.dtype)

Count: [38 29 55 12]
Count Data Type: int64

Price: [459.89 620.5  299.99  89.45]
Price Data Type: float64


In [29]:
# Changing Datatype - float into int
price = price.astype(int)
print("Price:", price)
print("Price Data Type:", price.dtype)

Price: [459 620 299  89]
Price Data Type: int64


## **9. Indexing**



**Understand the Concept**

- Indexing means accessing a specific value from an array.
- Indexing number starts from 0.



**Demonstrate the Concept**

**Real-Life Example:**

- Suppose a shopping list contains: ["Rice", "Milk", "Eggs", "Bread"]
- If we want the third item, we use index 2 because indexing starts from 0.

**AI/ML Usage:**

- Used to access a specific value or feature from an array during data processing.


In [30]:
# Implement the Concept:
# shopping list 
shopping = np.array(["Rice", "Milk", "Eggs", "Bread"])

# Access values using index
print(shopping[0]) # 1st ele
print(shopping[-1]) # last ele


Rice
Bread


## **10. Slicing**



**Understand the Concept**

- Slicing means getting a part of an array.
- We can select multiple values using a start and end index.
- The basic format is `array[start:end:step]`.




**Demonstrate the Concept**

**Real-Life Example:**

- Student's weekly study hours 

**AI/ML Usage:**

- Used to select a part of an array when preparing or processing data.



In [35]:
# Implement the Concept:
# weekly study hours data
study_hours = np.array([2, 3, 4, 5, 3, 6, 4])

print("last 3 days :", study_hours[4:])
print("day 4 & 5 :", study_hours[3:5])
print("even days :", study_hours[1::2])

last 3 days : [3 6 4]
day 4 & 5 : [5 3]
even days : [3 5 6]


## **11. Reshaping**



**Understand the Concept**

- Reshaping means changing the structure of an array.
- It changes the number of rows and columns without changing the values.



**Demonstrate the Concept**

**Real-Life Example:**

* A teacher has marks of 6 students stored in one row.
* The marks can be reshaped into 2 rows and 3 columns to organize the data better.

In [37]:
# Implement the Concept:
# Marks data - in 1D 
marks = np.array([10, 20, 30, 40, 50, 60])

# Reshape into 2D array
reshaped_marks = marks.reshape(2, 3)

print("Original Array:", marks)
print("Original Shape:", marks.shape)

print("\nReshaped Array:\n",reshaped_marks)
print("New Shape:", reshaped_marks.shape)

Original Array: [10 20 30 40 50 60]
Original Shape: (6,)

Reshaped Array:
 [[10 20 30]
 [40 50 60]]
New Shape: (2, 3)


## **12. Flatten**



**Understand the Concept**

- Flatten means converting a multi-dimensional array into a one-dimensional array..
- It keeps all the values but removes the rows and columns.




**Demonstrate the Concept**

**Real-Life Example:**

A school stores marks of students in rows and columns. If we want all the marks in a single list, we can use flatten.

**AI/ML Usage:**

- Used to convert multi-dimensional data into a single array before giving it to a Machine Learning model.

In [40]:
# Implement the Concept:
# marks data - 2d into 1d
marks = np.array([[80, 75, 90],
                  [85, 88, 92]])

# Convert the 2D array into a 1D array
flat_marks = marks.flatten()

print("Original Array:\n", marks)
print("\nFlattened Array:\n",flat_marks)


Original Array:
 [[80 75 90]
 [85 88 92]]

Flattened Array:
 [80 75 90 85 88 92]


## **13. Copy vs View**

**Understand the Concept**

**Copy:**
- A copy creates a separate array with the same values.
- Changes made to a copy do not affect the original array.

**View:**

- A view uses the same data as the original array.
- Changes made to a view can also change the original array.



**Demonstrate the Concept**

**Real-Life Example:**

**Copy:**

If you photocopy a document, changes to the photocopy do not affect the original document. This is similar to a copy.

**View:**

If two people use the same original document, a change made by one person can affect what the other person sees. This is similar to a view.

**AI/ML Usage:**

- Used to control how data is shared and changed during data preprocessing.


In [44]:
# Implement the Concept:
# Data
original = np.array([10, 20, 30])

# copy
copied_array = original.copy()
copied_array[0] = 100

print("Original after Copy Change:", original)
print("Copied Array:", copied_array)


Original after Copy Change: [10 20 30]
Copied Array: [100  20  30]


In [46]:
# view
view_array = original.view()
view_array[1] = 200

print("Original after View Change:", original)
print("View Array:", view_array)

Original after View Change: [ 10 200  30]
View Array: [ 10 200  30]


## **14. Broadcasting**



**Understand the Concept**

- Broadcasting allows arrays with different shapes to perform arithmetic operations automatically.



**Demonstrate the Concept**

**Real-Life Example:**

- A shop has three product prices.
- If the shop increases all prices by ₹10, we can add `10` to the complete array at once.

**AI/ML Usage:**

- Used to apply the same value or calculation to many data values during data preprocessing.



In [47]:
# Implement the Concept:
# product prices
prices = np.array([100, 200, 300])

# Add 10 using broadcasting
new_prices = prices + 10

print("Original Prices:", prices)
print("New Prices:", new_prices)

Original Prices: [100 200 300]
New Prices: [110 210 310]


## **15. Array Operations**



**Understand the Concept**

- NumPy allows us to perform calculations directly on arrays.
- We can add, subtract, multiply, and divide array values.





**Demonstrate the Concept**

**Real-Life Example:**

A shop has the quantity and price of three products:

- Quantity: `[2, 3, 4]`
- Price: `[100, 200, 150]`

We can multiply both arrays to calculate the total price for each product.

**AI/ML Usage:**

- Used for fast calculations on numerical data during data processing and feature preparation.


In [48]:
# Implement the Concept:
# data
quantity = np.array([2, 3, 4])
price = np.array([100, 200, 150])

# array operations
total_price = quantity * price
price_after_discount = price - 20

print("Quantity:", quantity)
print("Price:", price)
print("Total Price:", total_price)
print("Price After Discount:", price_after_discount)

Quantity: [2 3 4]
Price: [100 200 150]
Total Price: [200 600 600]
Price After Discount: [ 80 180 130]


## **16. Universal Functions (ufuncs)**



**Understand the Concept**

- ufuncs are  NumPy functions used to perform calculations on array values.
- A ufunc can work on every value in an array at the same time.
- Common ufuncs include np.sqrt(), np.abs(), np.exp() and np.sin().






**Demonstrate the Concept**

**Real-Life Example:**

- A shop records the difference between expected sales and actual sales.
- Using np.abs(), we can find the difference without considering whether it is positive or negative.

**AI/ML Usage:**

- Used to apply mathematical functions to large amounts of numerical data during data processing and model preparation.

In [49]:
# Implement the Concept:
# data
arr = np.array([1,2,3])

# Universal Functions
print(np.square(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.abs([-2,-5,6]))

[1 4 9]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[2 5 6]



## **Best Practices**

- Use `import numpy as np` when importing NumPy.
- Use NumPy arrays when working with numerical data.
- Check the shape and size of an array before performing operations.
- Use NumPy functions instead of unnecessary loops.
- Choose a suitable data type when working with large datasets.









## **Common Mistakes**

- Forgetting that array indexing starts from `0`.
- Using an incorrect shape while reshaping an array.
- Trying to reshape an array into a size that does not match the total number of values.
- Confusing `copy()` and `view()`.
- Using arrays with incompatible shapes during broadcasting.

## **Advantages**

- Fast numerical calculations.
- Easy to work with large numerical data.
- Supports one-dimensional and multi-dimensional arrays.
- Provides many mathematical functions.
- Useful for Data Science, AI, and Machine Learning.

## **Limitations**

- Mainly designed for numerical data.
- Requires understanding of arrays and dimensions.
- Not as convenient as Pandas for working with labelled table data.
- Some operations require understanding of array shapes.

## **Interview Questions with Answers**

**1. What is NumPy?**

NumPy is a Python library used for numerical calculations and working with arrays.

**2. What is an `ndarray`?**

`ndarray` is the main array data structure provided by NumPy. It can store values in one or more dimensions.

**3. What is the difference between `shape` and `size`?**

`shape` tells us how the array is arranged, while `size` tells us the total number of values.

**4. What is broadcasting in NumPy?**

Broadcasting allows NumPy to perform operations between arrays with compatible shapes without using loops.

**5. What is the difference between copy and view?**

A copy creates a separate array, while a view shares the same data with the original array.

**6. What is indexing in NumPy?**

Indexing is used to access a specific value from an array. NumPy indexing starts from `0`.

**7. What is slicing?**

Slicing is used to select a part of an array using start and end indexes.

**8. What is reshaping?**

Reshaping changes the structure of an array without changing its values.

**9. What does `ndim` tell us?**

`ndim` tells us the number of dimensions in a NumPy array.

**10. What are ufuncs in NumPy?**

ufuncs are NumPy functions that perform mathematical operations on array values.



## **Self Reflection**

- I learned the basics of NumPy and NumPy arrays.
- I understood dimensions, shape, size, and data types.
- I learned how to access and select array values using indexing and slicing.
- I learned how to reshape and flatten arrays.
- I understood the difference between copy and view.
- I learned how broadcasting and array operations work.
- I also learned how NumPy ufuncs can perform calculations on array values.