# **Notebook 2 – NumPy Mathematical Operations**

## **1. Sum**



**Understand the Concept**

* Sum means adding all the values together.
* NumPy provides np.sum() to quickly add values in an array.



**Demonstrate the Concept**

**Real-Life Example:**

* A shop sells 10, 20, 30, and 40 products on four days.
* The sum gives the total number of products sold.

**AI/ML Usage:**

* Sum is used to calculate totals in datasets.
* It can also be used in statistical calculations and feature processing.

In [25]:
# Libraries
import numpy as np

In [26]:
# Implement the Concept:
# sales data
sales = np.array([10, 20, 30, 40])

# Sum - total sales
total_sales = np.sum(sales)

print("Total Products Sold:", total_sales)

Total Products Sold: 100


## **2. Mean**





**Understand the Concept**

* Mean means finding the average of all the values.
* NumPy provides np.mean() to calculate the average of an array.

**Formula :** Sum of all values / Number of values

**Demonstrate the Concept**

**Real-Life Example:**

* A student scores  in four tests.
* The mean gives the student's average score.

**AI/ML Usage:**

* Mean is used to understand the average value of a dataset.
* It is also used in data preprocessing and statistical analysis.

In [27]:
# Implement the Concept:
# Test scores
scores = np.array([60, 70, 80, 90])

# Calculate the mean(avg)
average_score = np.mean(scores)

print("Average Score:", average_score)

Average Score: 75.0


## **3. Median**



**Understand the Concept**

* Median is the middle value of a group of numbers.
* First, arrange the values in ascending order.
* If there are two middle values, their average is taken.
* NumPy provides np.median() to find the median of an array.



**Demonstrate the Concept**

**Numerical Example:**

**Real-Life Example:**

* Five students spend amount on a trip.
* The median shows the middle spending value.

**AI/ML Usage:**

* Median is used to understand the middle value of a dataset.
* It is useful when the data contains very high or very low values.


In [28]:
# Implement the Concept:
# Daily spending
spending = np.array([100, 150, 200, 250, 300])

# median
median_spending = np.median(spending)

print("Median :", median_spending)

Median : 200.0


## **4. Variance**



**Understand the Concept**

* Variance shows how much the values are spread out from the mean.
* NumPy provides np.var() to calculate variance.
* small variance -  values are close to the mean.
* large variance -  values are more spread out.

  
**Formula :**

 Variance = Average of the squared differences from the mean.



**Demonstrate the Concept**

**Real-Life Example:**

* A teacher compares the marks of students in a class.
* Variance shows how much the marks differ from the average mark.

**AI/ML Usage:**

* Variance is used to understand how features are spread in a dataset.

In [29]:
# Implement the Concept:
# Student marks
marks = np.array([10, 20, 30])

# variance
variance = np.var(marks)

print("Variance:", variance)

Variance: 66.66666666666667


## **5. Standard Deviation**



**Understand the Concept**

* Standard deviation shows how far the values are from the mean.
* NumPy provides np.std() to calculate standard deviation.
* small standard deviation - the values are close to the mean.
* large standard deviation - the values are more spread out.

  
**Formula**

* Standard Deviation = Square root of Variance



**Demonstrate the Concept**

**Real-Life Example:**

* A teacher checks the marks of students in a class.
* Standard deviation shows how much the marks differ from the average mark.

**AI/ML Usage:**

* Standard deviation is used to understand the spread of features in a dataset.
* It is also used in data scaling and preprocessing.

In [30]:
# Implement the Concept:
# Student marks
marks = np.array([10, 20, 30])

# standard deviation
standard_deviation = np.std(marks)

print("Standard Deviation:", standard_deviation)

Standard Deviation: 8.16496580927726


## **6. Minimum**



**Understand the Concept**

* Minimum means finding the smallest value in an array.
* NumPy provides np.min() to find the smallest value.



**Demonstrate the Concept**

**Real-Life Example:**

* A shop checks the prices of different products.
* The minimum gives the lowest product price.

**AI/ML Usage:**

* Minimum is used to find the lowest value of a feature in a dataset

In [31]:
# Implement the Concept:
# Product prices
prices = np.array([15, 25, 10, 30, 20])

# Find the minimum price
minimum_price = np.min(prices)

print("Minimum Price:", minimum_price)

Minimum Price: 10


## **7. Maximum**



**Understand the Concept**

* Maximum means finding the largest value in an array.
* NumPy provides np.max() to find the largest value.


**Demonstrate the Concept**



**Real-Life Example:**

* A shop checks the prices of different products.
* The maximum gives the highest product price.

**AI/ML Usage:**

* Maximum is used to find the highest value of a feature in a dataset.
* It is also useful during data analysis and preprocessing.

In [32]:
# Implement the Concept:
# Product prices
prices = np.array([15, 25, 10, 30, 20])

# Find the maximum price
maximum_price = np.max(prices)

print("Maximum Price:", maximum_price)

Maximum Price: 30


## **8. Argmin**



**Understand the Concept**

* Argmin finds the position of the smallest value in an array.
* NumPy provides np.argmin() to find the index of the minimum value.
* The index starts from 0.



**Demonstrate the Concept**


**Real-Life Example:**

* A shop has different product prices.
* Argmin helps find the position of the product with the lowest price.

**AI/ML Usage:**

* Argmin is used to find the position of the smallest value in model results or numerical data.

In [33]:
# Implement the Concept:
# Product prices
prices = np.array([15, 25, 10, 30, 20])

# index - minimum value
minimum_index = np.argmin(prices)

print("Index of Minimum Price:", minimum_index)

Index of Minimum Price: 2


## **9. Argmax**



**Understand the Concept**

* Argmax finds the position of the largest value in an array.
* NumPy provides np.argmax() to find the index of the maximum value.
* The index starts from 0.



**Demonstrate the Concept**



**Real-Life Example:**

* A shop has different product prices.
* Argmax helps find the position of the product with the highest price.

**AI/ML Usage:**

* Argmax is used to find the position of the highest value in model predictions.

In [34]:
# Implement the Concept:
# Product prices
prices = np.array([15, 25, 10, 30, 20])

# index -  maximum value
maximum_index = np.argmax(prices)

print("Index of Maximum Price:", maximum_index)

Index of Maximum Price: 3


## **10. Percentile**



**Understand the Concept**

* Percentile shows the value below which a certain percentage of data falls.
* NumPy provides np.percentile() to calculate percentiles.





**Demonstrate the Concept**


**Real-Life Example:**

* A school checks the marks of students in an exam.
* The 75th percentile shows the mark below which most of the students' marks fall.

**AI/ML Usage:**

*  Using percentiles to detect and cap outliers (winsorization) in a feature before training a model, e.g., clipping values above the 99th percentile.

In [35]:
# Implement the Concept:
# Student marks
marks = np.array([10, 20, 30, 40, 50])

# 75th percentile
percentile_75 = np.percentile(marks, 75)

print("75th Percentile:", percentile_75)

75th Percentile: 40.0


## **11. Dot Product**



**Understand the Concept**

* Dot product means multiplying the matching values of two arrays and adding the results.
* NumPy provides np.dot() to calculate the dot product.
* Both arrays should have compatible sizes.

**Formula**

* Dot Product = (a₁ × b₁) + (a₂ × b₂) + ... + (aₙ × bₙ)



**Demonstrate the Concept**

**Example:**

* First array: 2, 3, 4
* Second array: 5, 6, 7
* Dot product = (2 × 5) + (3 × 6) + (4 × 7) = 56

**AI/ML Usage:**

* Dot product is widely used in Machine Learning to calculate weighted sums and is a basic operation in neural networks.

In [36]:
# Implement the Concept:
# two arrays
array_one = np.array([2, 3, 4])
array_two = np.array([5, 6, 7])

# dot product
result = np.dot(array_one, array_two)

print("Dot Product:", result)

Dot Product: 56


## **12. Matrix Multiplication**



**Understand the Concept**

* Matrix multiplication means multiplying two matrices to produce a new matrix.
* NumPy provides np.matmul() for matrix multiplication.
* The no of columns in the first matrix must match the no of rows in the second matrix.





**Demonstrate the Concept**

**Example:**

* First matrix: [[1, 2], [3, 4]]
* Second matrix: [[5, 6], [7, 8]]
* The result is [[19, 22], [43, 50]].



**AI/ML Usage:**

* Matrix multiplication is used in neural networks to calculate outputs from inputs and weights.

In [37]:
# Implement the Concept:
# two matrices
matrix_a = np.array([[1, 2],
                     [3, 4]])

matrix_b = np.array([[5, 6],
                     [7, 8]])

# matrix multiplication
result = np.matmul(matrix_a, matrix_b)

print("Matrix Multiplication:")
print(result)

Matrix Multiplication:
[[19 22]
 [43 50]]


## **13. Transpose**



**Understand the Concept**

* Transpose changes the rows of a matrix into columns and the columns into rows.
* NumPy provides np.transpose() to transpose an array.
* The values stay the same, but their positions change.



**Demonstrate the Concept**

**Example:**

* Matrix: [[1, 2, 3], [4, 5, 6]]
* Transpose: [[1, 4], [2, 5], [3, 6]]



**AI/ML Usage:**

* Transpose is used to change the shape and arrangement of matrices during Machine Learning calculations.

In [38]:
# Implement the Concept:
# matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Transpose - convert row to col & col to row
transposed_matrix = np.transpose(matrix)

print("Original Matrix:\n", matrix)
print("Shape :", matrix.shape)
print("\nTransposed Matrix:\n",transposed_matrix)
print("Shape :", transposed_matrix.shape)

Original Matrix:
 [[1 2 3]
 [4 5 6]]
Shape : (2, 3)

Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]
Shape : (3, 2)


## **14. Basic Linear Algebra Operations**



**Understand the Concept**

* Linear algebra deals with vectors, matrices, and mathematical operations.
* NumPy provides functions to perform common linear algebra calculations.



**Demonstrate the Concept**

**Example:**

* Matrix A = [[2, 1], [1, 2]]
* Matrix B = [5, 6]
* Determinant of A = 3
* Inverse of A = [[0.67, -0.33], [-0.33, 0.67]]
* Solution of Ax = B = [1.33, 1.67]
* Eigenvalues of A = 3 and 1
  
**AI/ML Usage:**

* Linear algebra is used in Machine Learning for calculations involving features, weights, matrices, and model training.

In [39]:
# Implement the Concept:
# matrix
matrix_1 = np.array([[2, 1],[1, 2]])
matrix_2 = np.array([5, 6])
# Determinant - matrix_1
determinant = np.linalg.det(matrix_1)

# Inverse - matrix_1
inverse = np.linalg.inv(matrix_1)

# Linear algebra
solution = np.linalg.solve(matrix_1, matrix_2)
eigenvalues, eigenvectors = np.linalg.eig(matrix_1)

print("Determinant:", determinant)
print("Inverse:\n",inverse )
print("Solution to Ax = b:", solution)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Determinant: 2.9999999999999996
Inverse:
 [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
Solution to Ax = b: [1.33333333 2.33333333]
Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## **Best Practices**

* Use NumPy functions for mathematical calculations.
* Check the shape of arrays before matrix operations.
* Use the correct function for each calculation.
* Keep numerical data in suitable NumPy arrays.
* Check the output after performing calculations.

## **Common Mistakes**

* Using arrays with incompatible shapes.
* Confusing argmin and minimum.
* Confusing argmax and maximum.
* Forgetting that indexing starts from 0.
* Using matrix multiplication when element-wise multiplication is needed.

## **Advantages**

* Makes mathematical calculations simple.
* Works efficiently with large numerical data.
* Provides many statistical functions.
* Supports matrix and linear algebra operations.
* Very useful for AI/ML calculations.

## **Limitations**

* Some operations require compatible array shapes.
* Matrix operations can be difficult for beginners.
* Large matrix calculations can use more memory.
* Understanding linear algebra is important for advanced operations.

## **Interview Questions with Answers**

**1. What does np.sum() do?**

* It adds all the values in an array and returns the total.

**2. What is the difference between mean and median?**

* Mean is the average of all values, while median is the middle value after arranging the data.

**3. What is variance?**

* Variance shows how much the values are spread around the mean.

**4. What is standard deviation?**

* Standard deviation shows how far the values are spread from the mean.

**5. What is the difference between argmin and minimum?**

* Minimum returns the smallest value, while argmin returns the position of the smallest value.

**6. What is the difference between argmax and maximum?**

* Maximum returns the largest value, while argmax returns the position of the largest value.

**7. What is a dot product?**

* Dot product multiplies matching values of two arrays and adds the results.

**8. What is matrix multiplication?**

* Matrix multiplication combines rows of one matrix with columns of another matrix to produce a new matrix.

**9. What is transpose?**

* Transpose changes rows into columns and columns into rows.

**10. What is linear algebra used for in AI/ML?**

* It is used for calculations involving vectors, matrices, weights, features, and model operations.


## **Self Reflection**

* I learned how to perform basic mathematical operations using NumPy.
* I understood mean, median, variance, and standard deviation.
* I learned how to find minimum, maximum, argmin, and argmax.
* I understood percentile and dot product.
* I learned matrix multiplication and transpose.